# Generated by Django 2.2.4 on 2019-08-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version1', models.CharField(max_length=10)),
                ('version2', models.CharField(max_length=10)),
                ('version3', models.CharField(max_length=10)),
            ],
        ),
    ]
