# Generated by Django 3.0.4 on 2020-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beta',
            name='version2',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
