# Generated by Django 2.2.4 on 2019-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdata',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
